@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NjljN2UyZTIyNGQ1Yzk2ZWE4M2M5YmMiLCJpYXQiOjE3MjE1OTYxODQsImV4cCI6MTcyMTY4MjU4NH0.U_ztltOWrgrB2Z5t5FMggfwn4O8ped8-6HCls3AS1kA
@hostname = 192.168.0.13
@port = {{$dotenv PORT}}
@url = http://{{hostname}}:{{port}}/api


### Create new user

POST {{url}}/users/new
Content-Type: application/json

{
  "name": "Aura",
  "email": "aura@gmail.com",
  "password": "1234",
  "picture": "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/325847998_749444776715812_8006280096664960905_n.jpg?stp=dst-jpg_s206x206&_nc_cat=107&ccb=1-7&_nc_sid=fe5ecc&_nc_eui2=AeG6cQgT0WS3d09idXjG3M4iFvg1-txZiuYW-DX63FmK5mE1dFGBtXt5bCfwZdDdPnzIQfYRTiyD1s3PgNodMMGH&_nc_ohc=gHBm_SQs0_wQ7kNvgFDVzFq&_nc_ht=scontent.fbog9-1.fna&oh=00_AYDRvZXwY1BhKIt6g3QMv1TY8_XwY6a2fAX51e-qnVtNsg&oe=66A38ECA"
}


### Login user

POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "jerast@gmail.com",
  "password": "1234"
}


### Revalidate user token

GET {{url}}/auth/renew
x-token: {{token}}


### get messages between users

GET {{url}}/messages/6694a39e90b25f361bf5d4dd
x-token: {{token}}
