@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NjlkYjA0ZTA5OTU0ZWVlOGQ0ODVmMzgiLCJpYXQiOjE3MjI0NzA3MDQsImV4cCI6MTcyMjU1NzEwNH0.JNre3qa3V9nFlAWDiKibribTpM7gu_GzzohBqsGc1EQ
@hostname = 192.168.0.13
@port = {{$dotenv PORT}}
@url = http://{{hostname}}:{{port}}/api


### Create new user

POST {{url}}/users/new
Content-Type: application/json

{
  "name": "Aura",
  "email": "aura@gmail.com",
  "password": "1234",
  "picture": "https://scontent.fbog9-1.fna.fbcdn.net/v/t39.30808-6/325847998_749444776715812_8006280096664960905_n.jpg?stp=dst-jpg_s206x206&_nc_cat=107&ccb=1-7&_nc_sid=fe5ecc&_nc_eui2=AeG6cQgT0WS3d09idXjG3M4iFvg1-txZiuYW-DX63FmK5mE1dFGBtXt5bCfwZdDdPnzIQfYRTiyD1s3PgNodMMGH&_nc_ohc=gHBm_SQs0_wQ7kNvgFDVzFq&_nc_ht=scontent.fbog9-1.fna&oh=00_AYDRvZXwY1BhKIt6g3QMv1TY8_XwY6a2fAX51e-qnVtNsg&oe=66A38ECA"
}


### Login user

POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "aura@gmail.com",
  "password": "1234"
}


### Revalidate user token

GET {{url}}/auth/renew
x-token: {{token}}


### get messages between users

GET {{url}}/messages/669db51d5a2eae1a9108b610
x-token: {{token}}
